# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autoregex.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='autoregex.proto',
  package='hitszids.wf.autoregex.api.v1',
  syntax='proto3',
  serialized_options=b'\n org.hitszids.wf.autoregex.api.v1B\016AutoRegexProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x61utoregex.proto\x12\x1chitszids.wf.autoregex.api.v1\"6\n\x07Request\x12\x12\n\nregex_name\x18\x01 \x01(\t\x12\x17\n\x0ftrain_data_file\x18\x02 \x01(\t\"v\n\x08Response\x12\x34\n\x06status\x18\x01 \x01(\x0b\x32$.hitszids.wf.autoregex.api.v1.Status\x12\x34\n\x06result\x18\x02 \x01(\x0b\x32$.hitszids.wf.autoregex.api.v1.Result\"3\n\x06Result\x12\x12\n\nregex_name\x18\x01 \x01(\t\x12\x15\n\rregex_pattern\x18\x02 \x01(\t\"M\n\x06Status\x12\x36\n\x04\x63ode\x18\x01 \x01(\x0e\x32(.hitszids.wf.autoregex.api.v1.StatusCode\x12\x0b\n\x03msg\x18\x02 \x01(\t*[\n\nStatusCode\x12\x06\n\x02OK\x10\x00\x12\x14\n\x0fPARAMETER_ERROR\x10\x90N\x12\x14\n\x0f\x46ILE_READ_ERROR\x10\x91N\x12\x19\n\x14REGEX_GENERATE_ERROR\x10\x92N2t\n\x10\x41utoRegexService\x12`\n\rRegexGenerate\x12%.hitszids.wf.autoregex.api.v1.Request\x1a&.hitszids.wf.autoregex.api.v1.Response\"\x00\x42\x34\n org.hitszids.wf.autoregex.api.v1B\x0e\x41utoRegexProtoP\x01\x62\x06proto3'
)

_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='hitszids.wf.autoregex.api.v1.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PARAMETER_ERROR', index=1, number=10000,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FILE_READ_ERROR', index=2, number=10001,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REGEX_GENERATE_ERROR', index=3, number=10002,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=357,
  serialized_end=448,
)
_sym_db.RegisterEnumDescriptor(_STATUSCODE)

StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
OK = 0
PARAMETER_ERROR = 10000
FILE_READ_ERROR = 10001
REGEX_GENERATE_ERROR = 10002



_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='hitszids.wf.autoregex.api.v1.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='regex_name', full_name='hitszids.wf.autoregex.api.v1.Request.regex_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='train_data_file', full_name='hitszids.wf.autoregex.api.v1.Request.train_data_file', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=103,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='hitszids.wf.autoregex.api.v1.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='hitszids.wf.autoregex.api.v1.Response.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='hitszids.wf.autoregex.api.v1.Response.result', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=223,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='hitszids.wf.autoregex.api.v1.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='regex_name', full_name='hitszids.wf.autoregex.api.v1.Result.regex_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='regex_pattern', full_name='hitszids.wf.autoregex.api.v1.Result.regex_pattern', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=276,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='hitszids.wf.autoregex.api.v1.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='hitszids.wf.autoregex.api.v1.Status.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='hitszids.wf.autoregex.api.v1.Status.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=355,
)

_RESPONSE.fields_by_name['status'].message_type = _STATUS
_RESPONSE.fields_by_name['result'].message_type = _RESULT
_STATUS.fields_by_name['code'].enum_type = _STATUSCODE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.enum_types_by_name['StatusCode'] = _STATUSCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'autoregex_pb2'
  # @@protoc_insertion_point(class_scope:hitszids.wf.autoregex.api.v1.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'autoregex_pb2'
  # @@protoc_insertion_point(class_scope:hitszids.wf.autoregex.api.v1.Response)
  })
_sym_db.RegisterMessage(Response)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'autoregex_pb2'
  # @@protoc_insertion_point(class_scope:hitszids.wf.autoregex.api.v1.Result)
  })
_sym_db.RegisterMessage(Result)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'autoregex_pb2'
  # @@protoc_insertion_point(class_scope:hitszids.wf.autoregex.api.v1.Status)
  })
_sym_db.RegisterMessage(Status)


DESCRIPTOR._options = None

_AUTOREGEXSERVICE = _descriptor.ServiceDescriptor(
  name='AutoRegexService',
  full_name='hitszids.wf.autoregex.api.v1.AutoRegexService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=450,
  serialized_end=566,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegexGenerate',
    full_name='hitszids.wf.autoregex.api.v1.AutoRegexService.RegexGenerate',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTOREGEXSERVICE)

DESCRIPTOR.services_by_name['AutoRegexService'] = _AUTOREGEXSERVICE

# @@protoc_insertion_point(module_scope)
