# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import autoregex_pb2 as autoregex__pb2


class AutoRegexServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegexGenerate = channel.unary_unary(
                '/hitszids.wf.autoregex.api.v1.AutoRegexService/RegexGenerate',
                request_serializer=autoregex__pb2.Request.SerializeToString,
                response_deserializer=autoregex__pb2.Response.FromString,
                )


class AutoRegexServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegexGenerate(self, request, context):
        """正则表达式生成接口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AutoRegexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegexGenerate': grpc.unary_unary_rpc_method_handler(
                    servicer.RegexGenerate,
                    request_deserializer=autoregex__pb2.Request.FromString,
                    response_serializer=autoregex__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hitszids.wf.autoregex.api.v1.AutoRegexService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AutoRegexService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegexGenerate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hitszids.wf.autoregex.api.v1.AutoRegexService/RegexGenerate',
            autoregex__pb2.Request.SerializeToString,
            autoregex__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
