from enum import Enum,unique

@unique
class RegexFlavour(Enum):
    Java = 'Java'
    Python = 'Python'

BPE_PAIR_PERCENT_THRESHOLD = 0.2
BPE_CHAR_PERCENT_THRESHOLD = 0.75
POPULATION_SIZE = 1000
MAX_ITERATIONS = 3000

MAX_DEPTH = 7
PRECISION_DIVIDE_CONQUER = 0.9
ITERATION_DIVIDE_CONQUER = 30

NOISE_POSITIVE_SAMPLE_RATIO = 0.05